### ISSUE TITLE
Comentarios

### ISSUE THREAD

**Issue by CarlosRubioTNM** [Mega1626/paginaweb#1]
Muy bien, jóvenes. Buena elección de colores.

Les adjunto unas cuantas correcciones para que realicen:
- Usar imágenes en formato png con fondo transparente.
- Colocar una breve descripción de cada integrante del equipo.
- Integrar un párrafo inventado sobre la historia de su empresa.

Espero su respuesta.

**Comment by Mega1626** [comment]
muchas gracias, tendremos en cuenta los comentarios para la siguiente actualizacion!

**Comment by Mega1626** [comment]
Cambios realizados, esperemos le gusten!

**Comment by CarlosRubioTNM** [comment]
Excelente, jóvenes. Buen trabajo. Cierro el Issue 👍
